language: php
sudo: false
dist: trusty
addons:
  firefox: 47.0.1
  postgresql: '9.4'
  apt:
    packages:
      - openjdk-8-jre-headless
cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.npm"
php:
  - 7.1
  - 7.2
  - 7.3
matrix:
  exclude:
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=master
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=master
  fast_finish: true
env:
  global:
    - BEHAT=no
    - MUSTACHE_IGNORE_NAMES="email_html_body.mustache, email_html.mustache, email_text.mustache"
    - SERVER_IP_ADDRESS=95.130.173.254
  matrix:
    - DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
    - DB=pgsql MOODLE_BRANCH=master
    - DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - DB=mysqli MOODLE_BRANCH=master
before_install:
  - openssl aes-256-cbc -K $encrypted_7d5fd5a42fc4_key -iv $encrypted_7d5fd5a42fc4_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  # test ssh connection for: https://github.com/dwyl/learn-travis/issues/42
  - ssh -i ./deploy_key root@138.68.163.126 -p3333 pwd
  - phpenv config-rm xdebug.ini
  - nvm install v8.9.4
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

jobs:
  include:
    - stage: static
      php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
      install:
        - moodle-plugin-ci install --no-init
      script:
        - moodle-plugin-ci phplint
        - moodle-plugin-ci phpmd
        - moodle-plugin-ci savepoints
        - moodle-plugin-ci mustache
        - moodle-plugin-ci grunt
    - stage: develop
      php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
      install:
        - moodle-plugin-ci install
      script:
        - moodle-plugin-ci phpunit --coverage-clover
        - moodle-plugin-ci behat
install:
  - moodle-plugin-ci install
script:
  - moodle-plugin-ci phpunit --coverage-clover
  - moodle-plugin-ci behat
after_success:
  - bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN
stages:
  - static
  - name: develop
    if: branch != master AND (type != pull_request OR head_branch != master) AND (tag
      IS blank)
  - name: test
    if: branch = master OR (type = pull_request AND head_branch = master) OR (tag IS
      present)
