language: php
sudo: false
dist: trusty
addons:
  apt:
    packages:
      - openjdk-8-jre-headless
cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.npm"
php:
  - 7.2
  - 7.3
matrix:
  exclude:
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=master
  fast_finish: true
env:
  global:
    - BEHAT=no
  matrix:
    - DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - DB=mysqli MOODLE_BRANCH=master
before_install:
  - phpenv config-rm xdebug.ini
  - nvm install v8.9.4
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
jobs:
  include:
    - stage: static
      php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
      install:
        - moodle-plugin-ci install --no-init
      script:
        - moodle-plugin-ci phplint
        - moodle-plugin-ci phpmd
        - moodle-plugin-ci savepoints
        - moodle-plugin-ci mustache
        - moodle-plugin-ci grunt
    - stage: develop
      php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
      install:
        - moodle-plugin-ci install
      script:
        - moodle-plugin-ci phpunit --coverage-clover
    - stage: deploy
      before_install: skip
      install: skip
      script :
        - cd $TRAVIS_BUILD_DIR
        - openssl aes-256-cbc -K $encrypted_7d5fd5a42fc4_key -iv $encrypted_7d5fd5a42fc4_iv
          -in deploy_key.enc -out /tmp/deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/deploy_rsa
        - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        - ssh-add /tmp/deploy_rsa
      deploy:
        provider: script
        skip_cleanup: true
        script: rsync -r --delete-after --quiet -e"ssh -v -i /tmp/deploy_rsa -p$SERVER_PORT" $TRAVIS_BUILD_DIR/ root@$SERVER_IP_ADDRESS:$DEVEDOPPATH
install:
  - moodle-plugin-ci install
script:
  - moodle-plugin-ci phpunit --coverage-clover
after_success:
  - bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN
stages:
  - name: static
    if: branch != master
  - name: develop
    if: branch != master AND (type != pull_request OR head_branch != master) AND (tag
      IS blank)
  - name: test
    if: branch = master OR (type = pull_request AND head_branch = master) OR (tag IS
      present)
  - name: deploy
    if: branch = master